/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-04-18 09:49:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.jsp.internatebanking.entity.Users;

public final class userprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.jsp.internatebanking.entity.Users");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    if (session.getAttribute("user") == null) {
        response.sendRedirect("login.jsp");
        return;
    }

      out.write("\r\n");
      out.write("\r\n");

    Users user = (Users) session.getAttribute("user");
    if (user == null) {
        response.sendRedirect("login.jsp");
        return;
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>User Profile — NexaBank</title>\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600;700&family=DM+Sans:wght@300;400;500;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/userprofile.css\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/dashboard.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbar.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- Top Navigation Bar -->\r\n");
      out.write("<nav class=\"topnav\">\r\n");
      out.write("    <div class=\"topnav__brand\">\r\n");
      out.write("        <span class=\"topnav__logo-icon\">&#9670;</span>\r\n");
      out.write("        <span class=\"topnav__logo-text\">NexaBank</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"topnav__user\">\r\n");
      out.write("        <span class=\"topnav__greeting\">Welcome, <strong>");
      out.print(user.getName());
      out.write("</strong></span>\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.write("/logout\" class=\"topnav__logout\">Sign Out</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Page Header -->\r\n");
      out.write("<header class=\"page-header\">\r\n");
      out.write("    <div class=\"page-header__inner\">\r\n");
      out.write("        <p class=\"page-header__eyebrow\">Account Management</p>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!-- Main Content -->\r\n");
      out.write("<main class=\"main-content\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Profile Card -->\r\n");
      out.write("    <section class=\"card profile-card\">\r\n");
      out.write("        <div class=\"card__header\">\r\n");
      out.write("            <div class=\"card__header-icon\">&#9673;</div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <h2 class=\"card__title\">Personal Information</h2>\r\n");
      out.write("                <p class=\"card__subtitle\">Update your name and email address</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"profile-layout\">\r\n");
      out.write("\r\n");
      out.write("            <!-- LEFT: Profile Form -->\r\n");
      out.write("            <div class=\"profile-form-col\">\r\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath());
      out.write("/updateProfile\" method=\"post\" class=\"profile-form\" id=\"profileForm\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"id\" value=\"");
      out.print(user.getId());
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"form-label\" for=\"nameInput\">Full Name</label>\r\n");
      out.write("                        <div class=\"input-wrapper\">\r\n");
      out.write("                            <span class=\"input-icon\">&#9786;</span>\r\n");
      out.write("                            <input class=\"form-input\" type=\"text\" id=\"nameInput\" name=\"name\" value=\"");
      out.print(user.getName());
      out.write("\" required placeholder=\"Your full name\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"form-label\" for=\"emailInput\">Email Address</label>\r\n");
      out.write("                        <div class=\"input-wrapper\">\r\n");
      out.write("                            <span class=\"input-icon\">&#9993;</span>\r\n");
      out.write("                            <input class=\"form-input\" type=\"email\" id=\"emailInput\" name=\"email\" value=\"");
      out.print(user.getEmail());
      out.write("\" required placeholder=\"your@email.com\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"form-label\">Account Balance</label>\r\n");
      out.write("                        <div class=\"input-wrapper\">\r\n");
      out.write("                            <span class=\"input-icon\">&#8377;</span>\r\n");
      out.write("                            <input class=\"form-input form-input--readonly\" type=\"text\" value=\"");
      out.print(user.getBalance());
      out.write("\" readonly />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"form-hint\">Balance is read-only and managed by the system.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"submit\" value=\"Save Changes\" class=\"btn btn--primary\" id=\"updateProfileBtn\" />\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- RIGHT: Profile Image -->\r\n");
      out.write("            <div class=\"profile-image-col\">\r\n");
      out.write("                <div class=\"avatar-card\">\r\n");
      out.write("                    <div class=\"avatar-wrapper\" id=\"avatarWrapper\">\r\n");
      out.write("                        ");
 if (user.getProfileImage() != null) { 
      out.write("\r\n");
      out.write("                            <img class=\"avatar-img\" id=\"avatarImg\"\r\n");
      out.write("                                 src=\"");
      out.print(request.getContextPath());
      out.write("/getProfileImage?id=");
      out.print(user.getId());
      out.write("\"\r\n");
      out.write("                                 alt=\"Profile Photo\" />\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                            <div class=\"avatar-placeholder\" id=\"avatarPlaceholder\">\r\n");
      out.write("                                <span class=\"avatar-initials\">");
      out.print(user.getName().substring(0,1).toUpperCase());
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        <div class=\"avatar-overlay\">\r\n");
      out.write("                            <span>Change</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"avatar-name\">");
      out.print(user.getName());
      out.write("</p>\r\n");
      out.write("                    <p class=\"avatar-email\">");
      out.print(user.getEmail());
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath());
      out.write("/uploadProfileImage\" method=\"post\"\r\n");
      out.write("                      enctype=\"multipart/form-data\" class=\"upload-form\" id=\"uploadForm\">\r\n");
      out.write("                    <label class=\"upload-label\" for=\"profileImageInput\">\r\n");
      out.write("                        <span class=\"upload-icon\">&#8679;</span>\r\n");
      out.write("                        <span class=\"upload-text\">Choose Photo</span>\r\n");
      out.write("                        <input class=\"upload-input\" type=\"file\" id=\"profileImageInput\" name=\"profileImage\" required accept=\"image/*\" />\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <input type=\"submit\" value=\"Upload Photo\" class=\"btn btn--secondary\" id=\"uploadBtn\" />\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Change Password Card -->\r\n");
      out.write("    <section class=\"card password-card\">\r\n");
      out.write("        <div class=\"card__header\">\r\n");
      out.write("            <div class=\"card__header-icon card__header-icon--gold\">&#9679;</div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <h2 class=\"card__title\">Change Password</h2>\r\n");
      out.write("                <p class=\"card__subtitle\">Secure your account with a new password</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"");
      out.print(request.getContextPath());
      out.write("/changePassword\" method=\"post\" class=\"password-form\" id=\"passwordForm\">\r\n");
      out.write("            <input type=\"hidden\" name=\"id\" value=\"");
      out.print(user.getId());
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("            <div class=\"password-form__grid\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"form-label\" for=\"currentPassword\">Current Password</label>\r\n");
      out.write("                    <div class=\"input-wrapper\">\r\n");
      out.write("                        <span class=\"input-icon\">&#128274;</span>\r\n");
      out.write("                        <input class=\"form-input\" type=\"password\" id=\"currentPassword\" name=\"currentPassword\" required placeholder=\"Enter current password\" />\r\n");
      out.write("                        <button type=\"button\" class=\"toggle-password\" data-target=\"currentPassword\" aria-label=\"Toggle visibility\">&#128065;</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"form-label\" for=\"newPassword\">New Password</label>\r\n");
      out.write("                    <div class=\"input-wrapper\">\r\n");
      out.write("                        <span class=\"input-icon\">&#128275;</span>\r\n");
      out.write("                        <input class=\"form-input\" type=\"password\" id=\"newPassword\" name=\"newPassword\" required placeholder=\"Enter new password\" />\r\n");
      out.write("                        <button type=\"button\" class=\"toggle-password\" data-target=\"newPassword\" aria-label=\"Toggle visibility\">&#128065;</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"password-footer\">\r\n");
      out.write("                <p class=\"password-note\">\r\n");
      out.write("                    <span class=\"password-note__icon\">&#9432;</span>\r\n");
      out.write("                    An OTP will be sent to your registered email to confirm the change.\r\n");
      out.write("                </p>\r\n");
      out.write("                <input type=\"submit\" value=\"Send OTP &rarr;\" class=\"btn btn--primary\" id=\"sendOtpBtn\" />\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("    <a href=\"dashboard.jsp\" class=\"back-btn\">Back To Dashboard</a>\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"site-footer\">\r\n");
      out.write("    <p>&copy; 2025 NexaBank &mdash; All transactions are secured with 256-bit encryption.</p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // Toggle password visibility\r\n");
      out.write("    document.querySelectorAll('.toggle-password').forEach(function(btn) {\r\n");
      out.write("        btn.addEventListener('click', function() {\r\n");
      out.write("            var targetId = this.getAttribute('data-target');\r\n");
      out.write("            var input = document.getElementById(targetId);\r\n");
      out.write("            if (input.type === 'password') {\r\n");
      out.write("                input.type = 'text';\r\n");
      out.write("                this.style.opacity = '1';\r\n");
      out.write("            } else {\r\n");
      out.write("                input.type = 'password';\r\n");
      out.write("                this.style.opacity = '0.5';\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Show filename on file select\r\n");
      out.write("    document.getElementById('profileImageInput').addEventListener('change', function() {\r\n");
      out.write("        var name = this.files[0] ? this.files[0].name : 'No file chosen';\r\n");
      out.write("        document.querySelector('.upload-text').textContent = name;\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
